config/routes.rb
Rails.application.routes.draw do
  #nuestras rutas para el scaffold
  resources :bloggers
  get 'noticias', to: 'bloggers#index'
  get 'nueva', to: 'bloggers#new'

  get 'home', to: 'pages#home'
  get 'contact', to: 'pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Nuestra ruta raiz del proyecto
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blogger.rb
class Blogger < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/noticia.rb
class Noticia < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  before_action :set_blogger, only: %i[ show edit update destroy ]

  # GET /bloggers or /bloggers.json
  def index
    @bloggers = Blogger.all
  end

  # GET /bloggers/1 or /bloggers/1.json
  def show
  end

  # GET /bloggers/new
  def new
    @blogger = Blogger.new
  end

  # GET /bloggers/1/edit
  def edit
  end

  # POST /bloggers or /bloggers.json
  def create
    @blogger = Blogger.new(blogger_params)

    respond_to do |format|
      if @blogger.save
        format.html { redirect_to blogger_url(@blogger), notice: "Blogger was successfully created." }
        format.json { render :show, status: :created, location: @blogger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggers/1 or /bloggers/1.json
  def update
    respond_to do |format|
      if @blogger.update(blogger_params)
        format.html { redirect_to blogger_url(@blogger), notice: "Blogger was successfully updated." }
        format.json { render :show, status: :ok, location: @blogger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloggers/1 or /bloggers/1.json
  def destroy
    @blogger.destroy

    respond_to do |format|
      format.html { redirect_to bloggers_url, notice: "Blogger was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogger
      @blogger = Blogger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blogger_params
      params.require(:blogger).permit(:titulo, :contenido, :link, :tipo, :estado)
    end
end

app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :set_noticia, only: %i[ show edit update destroy ]

  # GET /noticia or /noticia.json
  def index
    @noticias = Noticia.all
  end

  # GET /noticia/1 or /noticia/1.json
  def show
  end

  # GET /noticia/new
  def new
    @noticias = Noticia.new
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia or /noticia.json
  def create
    @noticium = Noticia.new(noticia_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to noticia_url(@noticia), notice: "Noticia was successfully created." }
        format.json { render :show, status: :created, location: @noticia }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1 or /noticia/1.json
  def update
    respond_to do |format|
      if @noticia.update(noticia)
        format.html { redirect_to noticium_url(@noticia), notice: "Noticium was successfully updated." }
        format.json { render :show, status: :ok, location: @noticia }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1 or /noticia/1.json
  def destroy
    @noticia.destroy

    respond_to do |format|
      format.html { redirect_to noticia_url, notice: "Noticia was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticia
      @noticium = Noticia.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def noticia_params
      params.require(:noticia).permit(:titulo, :contenido, :link, :tipo, :estado)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bloggers/_blogger.html.erb
<div class="card" id="<%= dom_id blogger %>"> <!-- inicio boocle -->
<div class="card border-info mb-8" style="max-width: 18rem;">
 <div class="card-header">  <p>
    <strong>Titulo:</strong>
    <%= blogger.titulo %>
  </p></div>
  <div class="card-body">
    <h5 class="card-title">  <p>
    <strong>Contenido:</strong>
    <%= blogger.contenido %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= blogger.link %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= blogger.tipo %>
  </p>
</h5>
    <p class="card-text">estado   <p>
    <strong>Estado:</strong>
    <%= blogger.estado %>
  </p>  <%= link_to "Ver articulo completo", blogger %></p>
  </div>
</div> <!-- termina card -->
</div> <!-- termina boble-->


 

app/views/bloggers/_form.html.erb
<%= form_with(model: blogger) do |form| %>
  <% if blogger.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blogger.errors.count, "error") %> prohibited this blogger from being saved:</h2>

      <ul>
        <% blogger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :contenido, style: "display: block" %>
    <%= form.text_field :contenido %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.number_field :tipo %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.number_field :estado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bloggers/edit.html.erb
<h1>Editing blogger</h1>

<%= render "form", blogger: @blogger %>

<br>

<div>
  <%= link_to "Show this blogger", @blogger %> |
  <%= link_to "Back to bloggers", bloggers_path %>
</div>

app/views/bloggers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bloggers</h1>
<%= link_to "New blogger", new_blogger_path %>
<hr>
<div class="card-group">
  <% @bloggers.each do |blogger| %>
    <%= render blogger %>
  <% end %>
</div> <!-- fin cad group -->

app/views/bloggers/new.html.erb
<h1>New blogger</h1>

<%= render "form", blogger: @blogger %>

<br>

<div>
  <%= link_to "Back to bloggers", bloggers_path %>
</div>

app/views/bloggers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blogger %>

<div>
  <%= link_to "Edit this blogger", edit_blogger_path(@blogger) %> |
  <%= link_to "Back to bloggers", bloggers_path %>

  <%= button_to "Destroy this blogger", @blogger, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doomscrolling</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container-fluid">
  <main class="container">
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path %>
        </li> / 
        <li class="nav-item">
          <%= link_to "Contact", contact_path %>
        </li> / 
        <li class="nav-item">
          <a class="nav-link disabled">------</a>
        </li> / 
                <li class="nav-item">
          <%= link_to "bloggers", bloggers_path %> /
        </li>
        <li class="nav-item">
          <%= link_to "nueva", nueva_path %> /
        </li>
      </ul>
    </div>
  </div>
</nav>
  <%= yield %></main>
  </div>
  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/noticia/_form.html.erb
<%= form_with(model: noticias) do |form| %>
  <% if noticia.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(noticia.errors.count, "error") %> prohibited this noticia from being saved:</h2>

      <ul>
        <% noticia.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :contenido, style: "display: block" %>
    <%= form.text_field :contenido %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.number_field :tipo %>
  </div>

  <div>
    <%= form.label :estado, style: "display: block" %>
    <%= form.number_field :estado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/noticia/_noticia.html.erb
<div id="<%= dom_id noticia %>">
  <p>
    <strong>Titulo:</strong>
    <%= noticia.titulo %>
  </p>

  <p>
    <strong>Contenido:</strong>
    <%= noticia.contenido %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= noticia.link %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= noticia.tipo %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= noticia.estado %>
  </p>

</div>

app/views/noticia/edit.html.erb
<h1>Editing noticia</h1>

<%= render "form", noticia: @noticia %>

<br>

<div>
  <%= link_to "Show this noticia", @noticia %> |
  <%= link_to "Back to noticia", noticia_path %>
</div>

app/views/noticia/index.html.erb
<p style="color: green"><%= noticias %></p>

<h1>Noticia</h1>

<div id="noticia">
  <% @noticia.each do |noticias| %>
    <%= render noticia %>
    <p>
      <%= link_to "Show this noticia", noticia %>
    </p>
  <% end %>
</div>

<%= link_to "New noticia", new_noticia_path %>

app/views/noticia/new.html.erb
<h1>New noticia</h1>

<%= render "form", noticia: @noticia %>

<br>

<div>
  <%= link_to "Back to noticia", noticia_path %>
</div>

app/views/noticia/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @noticia %>

<div>
  <%= link_to "Edit this noticia", edit_noticia_path(@noticia) %> |
  <%= link_to "Back to noticia", noticia_path %>

  <%= button_to "Destroy this noticia", @noticia, method: :delete %>
</div>

app/views/pages/contact.html.erb
<h1>Contactanos</h1>
<hr>
<form class="row">
<div class="container text-center">
  <div class="row">
    <div class="col">
          <label for="firstname">
      First name
      <input class="form-control-plaintext border border-primary" type="text" id="firstname" name="firstname" placeholder="First name" required>
    </label>
    </div>
    <div class="col">
      <label for="lastname">
      Last name
      <input class="form-control-plaintext border border-primary" type="text" id="lastname" name="lastname" placeholder="Last name" required>
    </label>
    </div>
    <div class="col">
       <label for="email">Email address</label>
  <input class="form-control-plaintext border border-primary" type="email" id="email" name="email" placeholder="Email address" required>
  <small>We'll never share your email with anyone else.</small>
    </div>
  </div>
</div>
<!-- Button -->
  <button class="bt border border-primary" type="submit">Submit</button>
</form>

app/views/pages/home.html.erb
<h1>Inicio </h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="card text-bg-light mb-3" style="max-width: 18rem;">
  <div class="card-header">Header</div>
  <div class="card-body">
    <h5 class="card-title">Light card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <p>prueba de gema guard 1</p>